-- auto Generated on 2021-01-31
-- DROP TABLE IF EXISTS employee;
CREATE TABLE employee(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'name',
	email VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'email',
	phone VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'phone',
	`date` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'date',
	`status` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'status',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'employee';
